### ISSUE TITLE
Add support for line numbers

### ISSUE THREAD

**Issue by L-Steinmacher** [rehypejs/rehype-highlight#29]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently there is no easy way to add line numbers for the parsed code as each individual element is a span. the usual way in css to add line nubers is to add a before on the span such as 
```css
pre span::before {
  counter-increment: line;
  content: counter(line);
  display: inline-block;
  width: 2em; /* Adjust as needed to suit your design */
  text-align: right;
  margin-right: 0.5em; /* Adjust as needed to suit your design */
  color: #999; /* Adjust the color as needed */
}
```

### Solution

Add a wrapper span with special class to more easily add line numbers to code blocks.

### Alternatives

If there is a current solution that I'm missing please inform me.
